### ISSUE TITLE
metada_tabs: error using list-like format

### ISSUE THREAD

**Issue by sadeiasturias** [open-sdg/open-sdg-data-starter#38]
Following the latest version of the [configuration section of the documentation](https://open-sdg.readthedocs.io/en/latest/configuration/), the metadata_tabs setting may be specified using a list-like format:

```
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
```

In our case, this setting causes all metadata tabs to disappear in the staging site (excepted the edit tab). However, if one uses instead the format recommended in the [stable version of the documentation](https://open-sdg.readthedocs.io/en/stable/configuration/),

```
metadata_tabs:
  national:
    title: indicator.national_metadata
    blurb: indicator.national_metadata_blurb
```

then it works as expected, and only the national tab shows up (apart form the edit tab in the staging environment).

We forked the open-sdg site and data starters 28 days ago, and use the version 1.1.0 for the jekyll remote theme.

We just wanted to highlight this issue, but it already works just fine for us.
